set nocompatible "不与vi兼容
set ts=4 "<Tab> = 4
set sts=4 " <Tab> = 4
set sw=4 "缩进= 4
set noexpandtab " <Tab>作为字符,不用空格替换
set nu "行号
set autoindent " 自动缩进
au FileType java,c,cpp set cindent
"java c 文件使用缩进
inoremap ( ()<LEFT>
inoremap [ []<LEFT>
inoremap { {}<LEFT>
inoremap " ""<LEFT>
inoremap ' ''<LEFT>
"设置括号 引号自动补全
au BufWritePost .vimrc exe "source " . expand('%:p')
".vimrc保存自动生效
set whichwrap=b,s,<,>,[,]
"设置光标左右移动可换行
au BufReadPost *
\ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
\ |   exe "normal! g`\""
\ | endif
"打开文件回到最后修改处
set ls=2
"lineststatus 永远显示状态行
set showcmd
"显示执行命令
set autoread 
"有改动自动重读
